name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches: ['*']
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
jobs:
    build:
        name: Format, Typecheck, Lint, & Build
        runs-on: ubuntu-latest
        if: ${{ !github.event.pull_request.draft || github.run_attempt != '1' }}
        timeout-minutes: 10
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Calc tools versions
              id: tools-versions
              run: |
                  NODE_VERSION=$(jq -r '.engines.node | gsub("[^0-9.]"; "")' package.json)
                  echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT

            - name: Setup Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ steps.tools-versions.outputs.node-version }}

            - name: Setup pnpm
              uses: pnpm/setup@v2
              with:
                  install: false
                  cache: true

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm run fmt:check

            - name: Build (production)
              run: pnpm run bundle

            - name: Verify generated files are current
              run: git diff --exit-code -- ThirdPartyNotices.txt
